### PR TITLE
Added support for profile names with hyphens

### PR DESCRIPTION
**Pull request by abjorshammar**
Changed the regexp to work with profile names with hyphens in them.

### CODE REVIEW

**Comment by bortels** [comment]
This only supports a single hyphen. Changing the regexp to '^profile (.*)$' gets me everything - I trust myself not to put garbage in my profile names. :-)

**Comment by abjorshammar** [comment]
Ok sure, so should I change my PR to have '^profile (.*)$' instead?

**Comment by hybby** [comment]
Hey, thanks for the PR.  Sorry, I've just noticed it.  Will have a look and see about implementing your suggestion.

I agree with you both, but think `.*` might be a bit broad.  So my initial thought is to go for something like [this](https://stackoverflow.com/questions/2525327/regex-for-a-za-z0-9-with-dashes-allowed-in-between-but-not-at-the-start-or-e) regular expression where an unlimited number of dashes are allowed as long as the profile doesn't start or end with them.

**Comment by abjorshammar** [comment]
Sounds good to me, my use case is profiles named like: "prefix-customer", so as long as that works I'm happy :-) However I guess it would be nice for the regexp to accept everything that is accepted by AWS, but I haven't found any documentation about that.

**Comment by hybby** [comment]
Thanks for your help and patience, everyone.  Hopefully #10 fixes this for you.

**Pull request closed without merging**
